### PR TITLE
updated version range for request dependency

### PR DESCRIPTION
**Pull request by kdeng**
Just raised a PR to update version range for request dependency, which will resolve some vulnerabilities.

### CODE REVIEW

**Comment by grantcarthew** [comment]
Please merge this and keep you dependencies update.

**Comment by mostlyjason** [comment]
@grantcarthew thanks for the reminder I will have someone test and merge soon

**Comment by mostlyjason** [comment]
Merged will update npm soon

**Comment by kdeng** [comment]
Thanks for accepted this PR. 
@grantcarthew thanks for the reminder, and I will keep this in my mind for next time.

Cheers

**Comment by grantcarthew** [comment]
OK happy to help. Thanks for the update.

**Pull request merged**
