### PR TITLE
Update variable name

### PR DESCRIPTION
**Pull request by Shwetajain148**

### CODE REVIEW

**Comment by benjie** [comment]
👍  Please let us know when a fix is released

**Comment by mostlyjason** [comment]
@benjie we have released a new beta version of this package with this fix along with some others to buffer messages and retry them automatically in the case of a connection error. Would you be willing to test it out?

npm install winston-loggly-bulk@beta

**Comment by benjie** [comment]
👍  Am using that now, will let you know if I notice any issues.

**Comment by mostlyjason** [comment]
@benjie Did you get a chance to try it yet? We\re planning to make it a production release soon and want to make sure there are no issues.

**Comment by benjie** [comment]
Have been running it for the past 8 days and not noticed anything so I assume all is well 👍

**Pull request merged**
